use anyhow::{Context, Result};
use serde::Deserialize;
use std::path::{Path, PathBuf};

// ─────────────────────────────────────────────────────────────────────────────
// Top-level config
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct Config {
    pub pool: PoolConfig,
    pub bitcoin_rpc: RpcConfig,
    pub zmq: ZmqConfig,
    pub vardiff: VardiffConfig,
    pub security: SecurityConfig,
    pub metrics: MetricsConfig,
    pub logging: LoggingConfig,
    /// Stratum V2 settings. Optional — defaults to enabled if the section is absent.
    #[serde(default)]
    pub sv2: Sv2Config,
}

// ─────────────────────────────────────────────────────────────────────────────
// Pool
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct PoolConfig {
    pub listen_addr: String,
    pub coinbase_address: String,
    pub coinbase_tag: String,
    pub initial_difficulty: u64,
    pub extranonce1_size: usize,
    pub extranonce2_size: usize,
    pub max_connections: usize,
    pub idle_timeout_secs: u64,
    /// Directory where the raw hex of every block this pool finds is archived
    /// before submission, so a failed `submitblock` can be retried or replayed
    /// by hand (`bitcoin-cli submitblock "$(cat <file>)"`). Relative paths
    /// resolve against the service working directory, like `stats_db_path`.
    #[serde(default = "default_found_block_dir")]
    pub found_block_dir: String,
    /// Optional safety assertion. The pool always detects the actual network
    /// from the connected node (`getblockchaininfo`) and validates the payout
    /// address against it. When this is set ("mainnet" | "testnet" | "testnet4" |
    /// "signet" | "regtest"), boot additionally fails fast if the node reports a
    /// different chain — catching a config pointed at the wrong node.
    #[serde(default)]
    pub network: Option<String>,
}

fn default_found_block_dir() -> String {
    "found-blocks".into()
}

// ─────────────────────────────────────────────────────────────────────────────
// Stratum V2
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct Sv2Config {
    /// Accept Stratum V2 (Extended Channel, Noise-encrypted) connections on the
    /// same listen port as SV1. The protocol is auto-detected from the first
    /// byte of each connection ('{' → SV1 JSON, otherwise → SV2 Noise
    /// handshake). When false, the pool rejects SV2 and only serves SV1.
    pub enabled: bool,
    /// Persist the Noise authority key across restarts so miners can pin the
    /// pool's identity (configure the pool's authority public key on the
    /// miner). The key file is created on first start. When false, a fresh
    /// authority key is generated each start; miners that pin the pool
    /// identity will refuse to connect after every restart.
    #[serde(default = "default_persist_authority_key")]
    pub persist_authority_key: bool,
    /// Path of the authority secret key file (base58check, one line). Created
    /// with owner-only permissions on first start when `persist_authority_key`
    /// is true. Relative paths resolve against the service working directory,
    /// like `stats_db_path`. Supports `~` expansion.
    #[serde(default = "default_authority_key_file")]
    pub authority_key_file: String,
    /// Validity window (seconds) of the certificate signed per handshake:
    /// `valid_from = now`, `not_valid_after = now + cert_validity_secs`.
    /// Miners that verify pool identity check this window against their own
    /// clock, so short values expose device clock skew. Defaults to one year.
    #[serde(default = "default_cert_validity_secs")]
    pub cert_validity_secs: u32,
}

fn default_persist_authority_key() -> bool {
    true
}

fn default_authority_key_file() -> String {
    "sv2-authority.key".into()
}

fn default_cert_validity_secs() -> u32 {
    365 * 24 * 60 * 60
}

impl Default for Sv2Config {
    fn default() -> Self {
        Self {
            enabled: true,
            persist_authority_key: default_persist_authority_key(),
            authority_key_file: default_authority_key_file(),
            cert_validity_secs: default_cert_validity_secs(),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Bitcoin RPC — cookie-file auth
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct RpcConfig {
    pub url: String,
    /// Path to the .cookie file generated by Bitcoin Knots / Core.
    /// Supports `~` expansion.
    pub cookie_path: Option<String>,
    /// Explicit credentials (used only when cookie_path is absent / unreadable)
    pub user: Option<String>,
    pub password: Option<String>,
    /// Applies to every RPC call, including the inline submitblock attempts on
    /// the block-found path.
    pub timeout_secs: u64,
}

impl RpcConfig {
    /// Resolve the cookie path (expanding `~`) and read its contents.
    /// Returns `(user, password)` parsed from the `user:password` file.
    pub fn read_cookie(&self) -> Result<(String, String)> {
        let raw = self.cookie_path.as_deref().unwrap_or("~/.bitcoin/.cookie");

        let expanded = expand_tilde(raw);
        let contents = std::fs::read_to_string(&expanded)
            .with_context(|| format!("Reading cookie file: {}", expanded.display()))?;

        let (u, p) = contents
            .trim()
            .split_once(':')
            .context("Cookie file format should be `user:password`")?;

        Ok((u.to_owned(), p.to_owned()))
    }

    /// Return bitcoincore_rpc::Auth, preferring cookie file over explicit creds.
    pub fn rpc_auth(&self) -> Result<bitcoincore_rpc::Auth> {
        // Try cookie first
        if let Ok((u, p)) = self.read_cookie() {
            return Ok(bitcoincore_rpc::Auth::UserPass(u, p));
        }
        // Fall back to explicit credentials
        match (&self.user, &self.password) {
            (Some(u), Some(p)) => Ok(bitcoincore_rpc::Auth::UserPass(u.clone(), p.clone())),
            _ => anyhow::bail!(
                "No RPC credentials available. \
                 Provide a readable cookie_path or explicit user/password."
            ),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ZMQ
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct ZmqConfig {
    pub hashblock_endpoint: String,
    pub poll_fallback: bool,
    pub poll_interval_ms: u64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Vardiff
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct VardiffConfig {
    pub target_share_time_secs: u64,
    pub retarget_interval_secs: u64,
    pub min_difficulty: u64,
    pub max_difficulty: u64,
    pub max_retarget_factor: f64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Security
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct SecurityConfig {
    pub max_connections_per_ip: u32,
    pub max_shares_per_sec: u32,
    /// How long an address stays banned after an unambiguous protocol
    /// violation (an oversize SV1 line or SV2 frame). Rate-limit violations
    /// are refused or disconnected but never banned, because honest firmware
    /// trips them when reconnecting after a restart. 0 disables bans.
    pub ban_duration_secs: u64,
    pub max_invalid_shares: u32,
    pub max_message_bytes: usize,
    /// Maximum byte length of an accepted worker/user-identity name. Bounds the
    /// global stats maps and Prometheus label cardinality against untrusted
    /// names. Defaults to 128 (fits a bech32m address + `.worker` suffix).
    #[serde(default = "default_max_worker_name_len")]
    pub max_worker_name_len: usize,
    /// Maximum number of *distinct* worker identities one connection may
    /// authorize (SV1 `mining.authorize` / SV2 `OpenExtendedMiningChannel`).
    /// Each distinct name creates entries in the global stats maps and mints
    /// Prometheus label series, so an unbounded count lets a single connection
    /// grow them without limit. Real miners authorize once. Defaults to 8.
    #[serde(default = "default_max_authorizations_per_session")]
    pub max_authorizations_per_session: u32,
}

fn default_max_worker_name_len() -> usize {
    128
}

fn default_max_authorizations_per_session() -> u32 {
    8
}

// ─────────────────────────────────────────────────────────────────────────────
// Metrics
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct MetricsConfig {
    pub prometheus_addr: String,
    /// Optional SQLite path to persist all-time stats between restarts.
    /// If omitted or empty, persistence is disabled.
    pub stats_db_path: Option<String>,
    /// Allow changing the payout address / network from the dashboard
    /// Settings page. The dashboard has no authentication of its own, so on
    /// an untrusted LAN either disable this or front the dashboard with an
    /// authenticating proxy (Umbrel's app_proxy does this automatically).
    #[serde(default = "default_allow_runtime_settings")]
    pub allow_runtime_settings: bool,
    /// Extra hostnames accepted in the `Host` header on mutating dashboard
    /// routes (`POST /api/settings`, `POST /api/reset-best-hashrate`).
    ///
    /// Those routes refuse requests whose `Host` is a public DNS name, which
    /// stops DNS rebinding: a web page the operator happens to open cannot
    /// point its own domain at the pool's LAN address and change the payout
    /// address from inside the browser. IP literals, `localhost`, single-label
    /// names and reserved local suffixes (`.local`, `.lan`, `.home.arpa`,
    /// `.internal`, ...) are always accepted. List any other name the
    /// dashboard is reached by here, such as a Tailscale or split-horizon DNS
    /// name. Compared case-insensitively, port ignored.
    #[serde(default)]
    pub allowed_hosts: Vec<String>,
}

fn default_allow_runtime_settings() -> bool {
    true
}

// ─────────────────────────────────────────────────────────────────────────────
// Logging
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct LoggingConfig {
    pub level: String,
    pub json: bool,
    /// Optional directory to write logs to (e.g., "/var/log/solo-pool-rs/").
    /// If set, logs will be written to a file in this directory.
    /// Supports `~` expansion. Read through `log_dir()`, which treats an
    /// empty value as unset.
    pub log_dir: Option<String>,
    /// How many daily log files to keep when `log_dir` is set. The oldest is
    /// deleted when a new day's file is opened. Ignored without `log_dir`.
    #[serde(default = "default_log_max_files")]
    pub log_max_files: usize,
}

fn default_log_max_files() -> usize {
    14
}

impl LoggingConfig {
    /// The log directory, or None when unset. An empty or whitespace-only
    /// value counts as unset: the shipped example uses `log_dir = ""` for
    /// "log to stdout", and `Some("")` would otherwise create a log file in
    /// the working directory.
    pub fn log_dir(&self) -> Option<&str> {
        self.log_dir
            .as_deref()
            .map(str::trim)
            .filter(|d| !d.is_empty())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Load helpers
// ─────────────────────────────────────────────────────────────────────────────

impl Config {
    /// Reject configurations that would later panic or misbehave at runtime.
    fn validate(&self) -> Result<()> {
        if self.logging.log_max_files == 0 {
            anyhow::bail!("[logging] log_max_files must be at least 1");
        }

        // An entry like "http://pool.ts.net/" would never match an incoming
        // Host header, so the operator would be locked out of settings with no
        // hint why. Refuse it here where the message is visible.
        for entry in &self.metrics.allowed_hosts {
            let entry = entry.trim();
            if entry.is_empty() || entry.contains("://") || entry.contains('/') {
                anyhow::bail!(
                    "[metrics] allowed_hosts entry '{entry}' must be a bare hostname \
                     (optionally with :port), without scheme or path"
                );
            }
        }

        // SV2 `OpenExtendedMiningChannel` derives `prefix_len` as
        // `extranonce_total - granted` (granted >= 1). A zero total underflows
        // that `usize` subtraction, so refuse it at boot rather than per-channel.
        if self.pool.extranonce1_size + self.pool.extranonce2_size == 0 {
            anyhow::bail!(
                "[pool] extranonce1_size + extranonce2_size must be >= 1 (got 0): \
                 a zero total extranonce width underflows SV2 channel setup"
            );
        }

        let en_total = self.pool.extranonce1_size + self.pool.extranonce2_size;

        // SV2 carries both the pool prefix and the device extranonce as B0_32.
        // A wider total encodes fine on SV1 but makes every SV2 channel open
        // fail, so the pool would serve one protocol and not the other.
        if en_total > 32 {
            anyhow::bail!(
                "[pool] extranonce1_size + extranonce2_size must be <= 32 (got {en_total}): \
                 SV2 encodes the extranonce as B0_32 and channel open would always fail"
            );
        }

        // Every SV1 session gets its own extranonce1 so miners search disjoint
        // space. At zero they all share an empty prefix and duplicate work.
        if self.pool.extranonce1_size == 0 {
            anyhow::bail!(
                "[pool] extranonce1_size must be >= 1: with no pool-assigned prefix \
                 every miner searches the same extranonce space"
            );
        }

        // Consensus caps the coinbase scriptSig at 100 bytes (bad-cb-length).
        // build_coinbase lays it out as BIP34 height push + coinbase_tag +
        // extranonce region, where the region is at least the 4-byte sentinel.
        // Share validation only checks header PoW, so an oversized scriptSig
        // stays invisible until a block is found and the node rejects it —
        // the same silent-until-blockfound class as the prevhash byte-order bug.
        // 5 bytes covers the height push for any height this will ever see.
        const MAX_SCRIPT_SIG: usize = 100;
        const HEIGHT_PUSH_MAX: usize = 5;
        let script_sig_len = HEIGHT_PUSH_MAX + self.pool.coinbase_tag.len() + en_total.max(4);
        if script_sig_len > MAX_SCRIPT_SIG {
            anyhow::bail!(
                "[pool] coinbase scriptSig would be {script_sig_len} bytes, over the \
                 {MAX_SCRIPT_SIG}-byte consensus limit: shorten coinbase_tag \
                 (currently {} bytes) or reduce the extranonce width ({en_total} bytes). \
                 Every block found would be rejected with bad-cb-length.",
                self.pool.coinbase_tag.len()
            );
        }
        // A too-low `timeout_secs` is raised to a floor with a warning rather
        // than refused here: the value was inert before it started being
        // applied, so a pool that had been running fine on, say, 2 would
        // otherwise stop booting on upgrade. See `rpc::effective_timeout_secs`,
        // which is also where the warning can actually be seen — this runs
        // before tracing is initialised.

        if self.sv2.enabled
            && self.sv2.persist_authority_key
            && self.sv2.authority_key_file.trim().is_empty()
        {
            anyhow::bail!(
                "[sv2] authority_key_file must not be empty while \
                 persist_authority_key = true"
            );
        }

        self.validate_vardiff()
    }

    /// Reject a `[vardiff]` section that would panic or stall every session.
    ///
    /// `Vardiff` clamps with `u64::clamp(min, max)`, which panics when
    /// `min > max`, and it runs on every `mining.suggest_difficulty` and every
    /// retarget. A bad pair therefore drops each miner shortly after connect
    /// instead of failing once at boot where the operator can see it.
    fn validate_vardiff(&self) -> Result<()> {
        let v = &self.vardiff;
        if v.min_difficulty == 0 {
            anyhow::bail!(
                "[vardiff] min_difficulty must be >= 1: a zero difficulty has no \
                 share target and every submission would be rejected"
            );
        }
        if v.min_difficulty > v.max_difficulty {
            anyhow::bail!(
                "[vardiff] min_difficulty ({}) must be <= max_difficulty ({}): \
                 clamping to an inverted range panics on every session",
                v.min_difficulty,
                v.max_difficulty
            );
        }
        if !v.max_retarget_factor.is_finite() || v.max_retarget_factor < 1.0 {
            anyhow::bail!(
                "[vardiff] max_retarget_factor must be a finite number >= 1.0 (got {}): \
                 the retarget ratio is clamped to [1/factor, factor]",
                v.max_retarget_factor
            );
        }
        if v.target_share_time_secs == 0 {
            anyhow::bail!(
                "[vardiff] target_share_time_secs must be >= 1: a zero target \
                 drives every retarget to the floor"
            );
        }
        if v.retarget_interval_secs == 0 {
            anyhow::bail!(
                "[vardiff] retarget_interval_secs must be >= 1: a zero interval \
                 retargets on every share"
            );
        }
        Ok(())
    }
}

/// A warning to log once tracing is up when the config file holds explicit
/// RPC credentials and other local users can read it. Cookie auth is the
/// recommended path precisely because the cookie file is owner-only; a
/// password pasted into a 0644 config undoes that.
#[cfg(unix)]
pub fn credential_exposure_warning(path: &str, cfg: &Config) -> Option<String> {
    use std::os::unix::fs::PermissionsExt;
    let has_password = cfg
        .bitcoin_rpc
        .password
        .as_deref()
        .is_some_and(|p| !p.is_empty());
    let in_url = cfg.bitcoin_rpc.url.contains('@');
    if !has_password && !in_url {
        return None;
    }
    let mode = std::fs::metadata(path).ok()?.permissions().mode();
    if mode & 0o077 == 0 {
        return None;
    }
    Some(format!(
        "{path} holds Bitcoin RPC credentials but is readable by other local users \
         (mode {:03o}); run `chmod 600 {path}` or switch to cookie_path",
        mode & 0o777
    ))
}

#[cfg(not(unix))]
pub fn credential_exposure_warning(_path: &str, _cfg: &Config) -> Option<String> {
    None
}

pub fn load(path: &str) -> Result<Config> {
    let raw =
        std::fs::read_to_string(path).with_context(|| format!("Opening config file: {path}"))?;
    let mut value: toml::Value = toml::from_str(&raw).context("Parsing config TOML")?;
    apply_env_overrides(&mut value, std::env::vars())?;
    let config: Config = value.try_into().context("Interpreting config")?;
    config.validate()?;
    Ok(config)
}

/// Environment-variable prefix for config overrides.
const ENV_PREFIX: &str = "SOLO_POOL_";

/// Apply `SOLO_POOL_<SECTION>__<KEY>=value` environment overrides onto the
/// parsed TOML before it is deserialized into [`Config`]. The double
/// underscore separates section from key (both contain single underscores),
/// e.g. `SOLO_POOL_BITCOIN_RPC__URL` → `[bitcoin_rpc] url`.
///
/// Container platforms (Umbrel, Start9, plain Compose) configure apps through
/// environment variables; this lets a stock config file ship in the image with
/// the deployment-specific values injected at runtime.
///
/// Typing: when the key exists in the file, the override is parsed as that
/// value's type (and load fails loudly if it cannot be). When the key is
/// absent, `true`/`false` become booleans and numbers become numbers — wrap
/// the value in double quotes to force a string (e.g. an all-numeric RPC
/// password).
fn apply_env_overrides(
    value: &mut toml::Value,
    vars: impl Iterator<Item = (String, String)>,
) -> Result<()> {
    let root = value
        .as_table_mut()
        .context("Config root is not a TOML table")?;

    for (name, raw) in vars {
        let Some(rest) = name.strip_prefix(ENV_PREFIX) else {
            continue;
        };
        let Some((section, key)) = rest.split_once("__") else {
            anyhow::bail!(
                "{name}: expected {ENV_PREFIX}<SECTION>__<KEY> \
                 (double underscore between section and key)"
            );
        };
        let (section, key) = (section.to_ascii_lowercase(), key.to_ascii_lowercase());
        if section.is_empty() || key.is_empty() {
            anyhow::bail!("{name}: empty section or key");
        }

        let table = root
            .entry(section.clone())
            .or_insert_with(|| toml::Value::Table(Default::default()))
            .as_table_mut()
            .with_context(|| format!("[{section}] is not a table"))?;

        let parse_err =
            || format!("{name}: value does not parse as the type of {section}.{key} in the file");
        let parsed = match table.get(&key) {
            Some(toml::Value::Integer(_)) => {
                toml::Value::Integer(raw.parse().with_context(parse_err)?)
            }
            Some(toml::Value::Float(_)) => toml::Value::Float(raw.parse().with_context(parse_err)?),
            Some(toml::Value::Boolean(_)) => {
                toml::Value::Boolean(raw.parse().with_context(parse_err)?)
            }
            Some(toml::Value::String(_)) => toml::Value::String(raw),
            Some(_) => anyhow::bail!("{name}: cannot override non-scalar {section}.{key}"),
            None => infer_toml_scalar(raw),
        };
        // Names only — values may be credentials.
        tracing::info!("Config override from environment: {section}.{key}");
        table.insert(key, parsed);
    }
    Ok(())
}

/// Best-effort scalar typing for keys not present in the config file.
/// Surrounding double quotes force a string.
fn infer_toml_scalar(raw: String) -> toml::Value {
    if let Some(quoted) = raw
        .strip_prefix('"')
        .and_then(|r| r.strip_suffix('"'))
        .filter(|_| raw.len() >= 2)
    {
        return toml::Value::String(quoted.to_string());
    }
    if raw == "true" || raw == "false" {
        return toml::Value::Boolean(raw == "true");
    }
    if let Ok(i) = raw.parse::<i64>() {
        return toml::Value::Integer(i);
    }
    if let Ok(f) = raw.parse::<f64>() {
        return toml::Value::Float(f);
    }
    toml::Value::String(raw)
}

/// Expand a leading `~` to the home directory.
pub(crate) fn expand_tilde(path: &str) -> PathBuf {
    if let Some(rest) = path.strip_prefix("~/") {
        if let Some(home) = std::env::var_os("HOME") {
            return Path::new(&home).join(rest);
        }
    }
    PathBuf::from(path)
}

#[cfg(test)]
mod tests {
    use super::{apply_env_overrides, Config};

    fn example_config() -> Config {
        let src = include_str!("../config.toml.example");
        let value: toml::Value = toml::from_str(src).expect("example config must parse as TOML");
        value.try_into().expect("example config must match Config")
    }

    #[test]
    fn shipped_example_config_passes_validation() {
        // The example is what operators copy, so it must satisfy every guard.
        example_config().validate().expect("example must validate");
    }

    #[test]
    fn empty_log_dir_means_stdout() {
        // The example ships `log_dir = ""` with a comment promising stdout.
        let mut cfg = example_config();
        assert_eq!(cfg.logging.log_dir, Some(String::new()));
        assert_eq!(cfg.logging.log_dir(), None);
        cfg.logging.log_dir = Some("   ".to_string());
        assert_eq!(cfg.logging.log_dir(), None);
        cfg.logging.log_dir = Some("~/logs".to_string());
        assert_eq!(cfg.logging.log_dir(), Some("~/logs"));
        cfg.logging.log_dir = None;
        assert_eq!(cfg.logging.log_dir(), None);
    }

    #[test]
    fn log_retention_defaults_and_rejects_zero() {
        let src = "[logging]\nlevel = \"info\"\njson = false\n";
        let value: toml::Value = toml::from_str(src).unwrap();
        let logging: super::LoggingConfig = value["logging"].clone().try_into().unwrap();
        assert_eq!(logging.log_max_files, 14);

        let mut cfg = example_config();
        cfg.logging.log_max_files = 0;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(err.contains("log_max_files"), "unexpected error: {err}");
    }

    #[test]
    fn oversized_coinbase_scriptsig_is_rejected() {
        // Consensus caps scriptSig at 100 bytes. Without this guard the pool runs
        // and validates shares normally, and only the found block is rejected.
        let mut cfg = example_config();
        cfg.pool.coinbase_tag = "x".repeat(95);
        let err = cfg.validate().unwrap_err().to_string();
        assert!(err.contains("bad-cb-length"), "unexpected error: {err}");
    }

    #[test]
    fn extranonce_wider_than_sv2_allows_is_rejected() {
        let mut cfg = example_config();
        cfg.pool.extranonce1_size = 24;
        cfg.pool.extranonce2_size = 16;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(err.contains("<= 32"), "unexpected error: {err}");
    }

    #[test]
    fn a_too_low_rpc_timeout_still_boots() {
        // timeout_secs was inert until it started being applied, so a pool
        // running a low value was working. Refusing to boot would break it on
        // upgrade over a setting that had never done anything; the value is
        // raised to a floor at client construction instead.
        let mut cfg = example_config();
        cfg.bitcoin_rpc.timeout_secs = 1;
        assert!(
            cfg.validate().is_ok(),
            "a low timeout must not stop the pool from starting"
        );
    }

    #[cfg(unix)]
    #[test]
    fn credential_warning_fires_only_for_readable_files_with_a_password() {
        use super::credential_exposure_warning;
        use std::os::unix::fs::PermissionsExt;
        let dir = std::env::temp_dir().join(format!("solo-pool-cfg-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("config.toml");
        std::fs::write(&path, "").unwrap();
        let path_str = path.to_str().unwrap();

        let mut cfg = example_config();
        cfg.bitcoin_rpc.password = Some("hunter2".into());

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        let warning = credential_exposure_warning(path_str, &cfg).expect("0644 must warn");
        assert!(warning.contains("chmod 600"), "{warning}");

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        assert!(credential_exposure_warning(path_str, &cfg).is_none());

        // Cookie auth with a readable config is fine: nothing secret in it.
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        cfg.bitcoin_rpc.password = None;
        assert!(credential_exposure_warning(path_str, &cfg).is_none());

        // Credentials in the URL count too.
        cfg.bitcoin_rpc.url = "http://u:p@127.0.0.1:8332".into();
        assert!(credential_exposure_warning(path_str, &cfg).is_some());

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn allowed_hosts_with_scheme_or_path_are_rejected() {
        for bad in ["http://pool.ts.net", "pool.ts.net/", ""] {
            let mut cfg = example_config();
            cfg.metrics.allowed_hosts = vec![bad.to_string()];
            let err = cfg.validate().unwrap_err().to_string();
            assert!(
                err.contains("allowed_hosts"),
                "'{bad}': unexpected error: {err}"
            );
        }
        let mut cfg = example_config();
        cfg.metrics.allowed_hosts = vec!["pool.ts.net:9090".to_string()];
        assert!(cfg.validate().is_ok());
    }

    #[test]
    fn zero_extranonce1_is_rejected() {
        let mut cfg = example_config();
        cfg.pool.extranonce1_size = 0;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(err.contains("extranonce1_size"), "unexpected error: {err}");
    }

    #[test]
    fn inverted_vardiff_range_is_rejected() {
        // u64::clamp(min, max) panics when min > max, and Vardiff calls it on
        // every retarget and every suggest_difficulty. Catch it at boot.
        let mut cfg = example_config();
        cfg.vardiff.min_difficulty = 262_144;
        cfg.vardiff.max_difficulty = 1024;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(err.contains("min_difficulty"), "unexpected error: {err}");
    }

    #[test]
    fn equal_vardiff_floor_and_ceiling_is_allowed() {
        // A fixed-difficulty pool is a legitimate configuration.
        let mut cfg = example_config();
        cfg.vardiff.min_difficulty = 4096;
        cfg.vardiff.max_difficulty = 4096;
        assert!(cfg.validate().is_ok());
    }

    #[test]
    fn zero_vardiff_floor_is_rejected() {
        let mut cfg = example_config();
        cfg.vardiff.min_difficulty = 0;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("min_difficulty must be >= 1"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn bad_retarget_factor_is_rejected() {
        for bad in [0.0, 0.5, -4.0, f64::NAN, f64::INFINITY] {
            let mut cfg = example_config();
            cfg.vardiff.max_retarget_factor = bad;
            let err = cfg.validate().unwrap_err().to_string();
            assert!(
                err.contains("max_retarget_factor"),
                "factor {bad}: unexpected error: {err}"
            );
        }
    }

    #[test]
    fn zero_vardiff_timings_are_rejected() {
        let mut cfg = example_config();
        cfg.vardiff.target_share_time_secs = 0;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("target_share_time_secs"),
            "unexpected error: {err}"
        );

        let mut cfg = example_config();
        cfg.vardiff.retarget_interval_secs = 0;
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("retarget_interval_secs"),
            "unexpected error: {err}"
        );
    }

    // Fixtures pass vars directly instead of mutating the process environment,
    // so tests stay parallel-safe.
    fn apply(toml_src: &str, vars: &[(&str, &str)]) -> anyhow::Result<toml::Value> {
        let mut value: toml::Value = toml::from_str(toml_src).unwrap();
        apply_env_overrides(
            &mut value,
            vars.iter().map(|(k, v)| (k.to_string(), v.to_string())),
        )?;
        Ok(value)
    }

    #[test]
    fn overrides_use_the_type_of_the_existing_key() {
        let v = apply(
            "[pool]\nlisten_addr = \"0.0.0.0:3333\"\ninitial_difficulty = 512\n[sv2]\nenabled = true",
            &[
                ("SOLO_POOL_POOL__LISTEN_ADDR", "0.0.0.0:3335"),
                ("SOLO_POOL_POOL__INITIAL_DIFFICULTY", "1024"),
                ("SOLO_POOL_SV2__ENABLED", "false"),
            ],
        )
        .unwrap();
        assert_eq!(v["pool"]["listen_addr"].as_str().unwrap(), "0.0.0.0:3335");
        assert_eq!(v["pool"]["initial_difficulty"].as_integer().unwrap(), 1024);
        assert!(!v["sv2"]["enabled"].as_bool().unwrap());
    }

    #[test]
    fn unparseable_override_for_typed_key_fails_loudly() {
        let err = apply(
            "[pool]\ninitial_difficulty = 512",
            &[("SOLO_POOL_POOL__INITIAL_DIFFICULTY", "not-a-number")],
        )
        .unwrap_err();
        assert!(err.to_string().contains("pool.initial_difficulty"));
    }

    #[test]
    fn absent_keys_and_sections_are_created_with_inferred_types() {
        let v = apply(
            "[bitcoin_rpc]\nurl = \"http://127.0.0.1:8332\"",
            &[
                ("SOLO_POOL_BITCOIN_RPC__USER", "umbrel"),
                ("SOLO_POOL_SV2__ENABLED", "false"),
            ],
        )
        .unwrap();
        assert_eq!(v["bitcoin_rpc"]["user"].as_str().unwrap(), "umbrel");
        assert!(!v["sv2"]["enabled"].as_bool().unwrap());
    }

    #[test]
    fn quotes_force_string_for_numeric_looking_absent_values() {
        let v = apply(
            "[bitcoin_rpc]\nurl = \"http://127.0.0.1:8332\"",
            &[
                ("SOLO_POOL_BITCOIN_RPC__PASSWORD", "\"123456\""),
                ("SOLO_POOL_BITCOIN_RPC__TIMEOUT_SECS", "30"),
            ],
        )
        .unwrap();
        assert_eq!(v["bitcoin_rpc"]["password"].as_str().unwrap(), "123456");
        assert_eq!(v["bitcoin_rpc"]["timeout_secs"].as_integer().unwrap(), 30);
    }

    #[test]
    fn unrelated_and_malformed_prefixed_vars() {
        // Unrelated vars are ignored entirely.
        let v = apply("[pool]\nlisten_addr = \"a\"", &[("PATH", "/usr/bin")]).unwrap();
        assert_eq!(v["pool"]["listen_addr"].as_str().unwrap(), "a");
        // Prefixed vars without the section/key separator are an error, not
        // silently dropped — a typo should not boot with stale config.
        assert!(apply(
            "[pool]\nlisten_addr = \"a\"",
            &[("SOLO_POOL_LISTEN_ADDR", "b")]
        )
        .is_err());
    }
}
