use anyhow::{Context, Result};
use serde::Deserialize;
use std::path::{Path, PathBuf};

// ─────────────────────────────────────────────────────────────────────────────
// Top-level config
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct Config {
    pub pool: PoolConfig,
    pub bitcoin_rpc: RpcConfig,
    pub zmq: ZmqConfig,
    pub vardiff: VardiffConfig,
    pub security: SecurityConfig,
    pub metrics: MetricsConfig,
    pub logging: LoggingConfig,
    /// Stratum V2 settings. Optional — defaults to enabled if the section is absent.
    #[serde(default)]
    pub sv2: Sv2Config,
}

// ─────────────────────────────────────────────────────────────────────────────
// Pool
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct PoolConfig {
    pub listen_addr: String,
    pub coinbase_address: String,
    pub coinbase_tag: String,
    pub initial_difficulty: u64,
    pub extranonce1_size: usize,
    pub extranonce2_size: usize,
    pub max_connections: usize,
    pub idle_timeout_secs: u64,
    /// Directory where the raw hex of every block this pool finds is archived
    /// before submission, so a failed `submitblock` can be retried or replayed
    /// by hand (`bitcoin-cli submitblock "$(cat <file>)"`). Relative paths
    /// resolve against the service working directory, like `stats_db_path`.
    #[serde(default = "default_found_block_dir")]
    pub found_block_dir: String,
}

fn default_found_block_dir() -> String {
    "found-blocks".into()
}

// ─────────────────────────────────────────────────────────────────────────────
// Stratum V2
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct Sv2Config {
    /// Accept Stratum V2 (Extended Channel, Noise-encrypted) connections on the
    /// same listen port as SV1. The protocol is auto-detected from the first
    /// byte of each connection ('{' → SV1 JSON, otherwise → SV2 Noise
    /// handshake). When false, the pool rejects SV2 and only serves SV1.
    ///
    /// The Noise authority keypair is generated per process; miners such as the
    /// NerdQAxe++ do not pin/verify the pool identity, so no key configuration is
    /// required. (A persistent, configurable authority key can be added later for
    /// identity pinning.)
    pub enabled: bool,
}

impl Default for Sv2Config {
    fn default() -> Self {
        Self { enabled: true }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Bitcoin RPC — cookie-file auth
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct RpcConfig {
    pub url: String,
    /// Path to the .cookie file generated by Bitcoin Knots / Core.
    /// Supports `~` expansion.
    pub cookie_path: Option<String>,
    /// Explicit credentials (used only when cookie_path is absent / unreadable)
    pub user: Option<String>,
    pub password: Option<String>,
    #[allow(dead_code)]
    pub timeout_secs: u64,
}

impl RpcConfig {
    /// Resolve the cookie path (expanding `~`) and read its contents.
    /// Returns `(user, password)` parsed from the `user:password` file.
    pub fn read_cookie(&self) -> Result<(String, String)> {
        let raw = self.cookie_path.as_deref().unwrap_or("~/.bitcoin/.cookie");

        let expanded = expand_tilde(raw);
        let contents = std::fs::read_to_string(&expanded)
            .with_context(|| format!("Reading cookie file: {}", expanded.display()))?;

        let (u, p) = contents
            .trim()
            .split_once(':')
            .context("Cookie file format should be `user:password`")?;

        Ok((u.to_owned(), p.to_owned()))
    }

    /// Return bitcoincore_rpc::Auth, preferring cookie file over explicit creds.
    pub fn rpc_auth(&self) -> Result<bitcoincore_rpc::Auth> {
        // Try cookie first
        if let Ok((u, p)) = self.read_cookie() {
            return Ok(bitcoincore_rpc::Auth::UserPass(u, p));
        }
        // Fall back to explicit credentials
        match (&self.user, &self.password) {
            (Some(u), Some(p)) => Ok(bitcoincore_rpc::Auth::UserPass(u.clone(), p.clone())),
            _ => anyhow::bail!(
                "No RPC credentials available. \
                 Provide a readable cookie_path or explicit user/password."
            ),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ZMQ
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct ZmqConfig {
    pub hashblock_endpoint: String,
    #[allow(dead_code)]
    pub rawtx_endpoint: String,
    pub poll_fallback: bool,
    pub poll_interval_ms: u64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Vardiff
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct VardiffConfig {
    pub target_share_time_secs: u64,
    pub retarget_interval_secs: u64,
    pub min_difficulty: u64,
    pub max_difficulty: u64,
    pub max_retarget_factor: f64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Security
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct SecurityConfig {
    pub max_connections_per_ip: u32,
    pub max_shares_per_sec: u32,
    pub ban_duration_secs: u64,
    pub max_invalid_shares: u32,
    pub max_message_bytes: usize,
    /// Maximum byte length of an accepted worker/user-identity name. Bounds the
    /// global stats maps and Prometheus label cardinality against untrusted
    /// names. Defaults to 128 (fits a bech32m address + `.worker` suffix).
    #[serde(default = "default_max_worker_name_len")]
    pub max_worker_name_len: usize,
    /// Maximum number of *distinct* worker identities one connection may
    /// authorize (SV1 `mining.authorize` / SV2 `OpenExtendedMiningChannel`).
    /// Each distinct name creates entries in the global stats maps and mints
    /// Prometheus label series, so an unbounded count lets a single connection
    /// grow them without limit. Real miners authorize once. Defaults to 8.
    #[serde(default = "default_max_authorizations_per_session")]
    pub max_authorizations_per_session: u32,
}

fn default_max_worker_name_len() -> usize {
    128
}

fn default_max_authorizations_per_session() -> u32 {
    8
}

// ─────────────────────────────────────────────────────────────────────────────
// Metrics
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct MetricsConfig {
    pub prometheus_addr: String,
    /// Optional SQLite path to persist all-time stats between restarts.
    /// If omitted or empty, persistence is disabled.
    pub stats_db_path: Option<String>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Logging
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, Clone)]
pub struct LoggingConfig {
    pub level: String,
    pub json: bool,
    /// Optional directory to write logs to (e.g., "/var/log/solo-pool-rs/").
    /// If set, logs will be written to a file in this directory.
    /// Supports `~` expansion.
    pub log_dir: Option<String>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Load helpers
// ─────────────────────────────────────────────────────────────────────────────

impl Config {
    /// Reject configurations that would later panic or misbehave at runtime.
    fn validate(&self) -> Result<()> {
        // SV2 `OpenExtendedMiningChannel` derives `prefix_len` as
        // `extranonce_total - granted` (granted >= 1). A zero total underflows
        // that `usize` subtraction, so refuse it at boot rather than per-channel.
        if self.pool.extranonce1_size + self.pool.extranonce2_size == 0 {
            anyhow::bail!(
                "[pool] extranonce1_size + extranonce2_size must be >= 1 (got 0): \
                 a zero total extranonce width underflows SV2 channel setup"
            );
        }
        Ok(())
    }
}

pub fn load(path: &str) -> Result<Config> {
    let raw =
        std::fs::read_to_string(path).with_context(|| format!("Opening config file: {path}"))?;
    let config: Config = toml::from_str(&raw).context("Parsing config TOML")?;
    config.validate()?;
    Ok(config)
}

/// Expand a leading `~` to the home directory.
fn expand_tilde(path: &str) -> PathBuf {
    if let Some(rest) = path.strip_prefix("~/") {
        if let Some(home) = std::env::var_os("HOME") {
            return Path::new(&home).join(rest);
        }
    }
    PathBuf::from(path)
}
